apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fastapi.service_name}}
  labels:
    name: {{.Values.fastapi.service_name}}
    app: {{.Chart.Name}}
spec:
  type: ClusterIP
  selector:
    name: {{.Values.fastapi.pod_name}}
    app: {{.Chart.Name}}
  ports:
    - port: {{.Values.fastapi.ports.port}}
      targetPort: {{.Values.fastapi.ports.targetPort}}
      protocol: {{.Values.fastapi.ports.protocol}}
      name: http-metrics