apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.fastapi.deployment-name}}
  labels: 
    name: {{.Values.fastapi.deployment-name}}
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.fastapi.replicaCount}}
  selector: 
    matchLabels: 
     name: {{.Values.fastapi.pod-name}}
     app: {{.Chart.Name}}
  template: 
    metadata:
      name: {{.Values.fastapi.pod-name}}
      labels:
        name: {{.Values.fastapi.pod-name}}
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Values.fastapi.image_name}}
          image: {{.Values.fastapi.image}}
          imagePullPolicy: Never
          resources:
            requests:
              cpu: {{.Values.fastapi.resources.requests.cpu}}
              memory: {{.Values.fastapi.resources.requests.memory}}
            limits:
              cpu: {{.Values.fastapi.resources.limits.cpu}}
              memory: {{.Values.fastapi.resources.limits.memory}}
          env:
           - name: DATABASE_URL
             value: "postgresql://postgres:Micdrop7!@postgres-service:5432/postgres"
          ports:
           - containerPort: {{.Values.fastapi.ports.containerPort}}
  



