apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.postgres.deployment-name}}
  labels:
    name: {{.Values.postgres.deployment-name}}
    app: {{.Chart.Name}}
spec:
  replicas: {{.Values.postgres.replicaCount}}
  selector:
    matchLabels:
     name: {{.Values.postgres.pod-name}}
     app: {{.Chart.Name}}
  template:
    metadata:
      name: {{.Values.postgres.pod-name}}
      labels:
        name: {{.Values.postgres.pod-name}}
        app: {{.Chart.Name}}
    spec:
      containers:
        - name: {{.Values.postgres.image_name}}
          image: {{.Values.postgres.image}}
          env:
            - name: POSTGRES_USER
              value: {{.Values.postgres.env.name_value}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.postgres.env.password_value}}
            - name: POSTGRES_DB
              value: {{.Values.postgres.env.postgres-db-value}}
          ports:
            - containerPort: {{.Values.postgres.ports.containerPort}}
 