apiVersion: v1
kind: Service
metadata:
  name: {{.Values.postgres.service_name}}
  labels:
    name: {{.Values.postgres.service_name}}
    app: {{.Chart.Name}}
spec:
  type: ClusterIP
  selector:
    name: {{.Values.postgres.pod_name}}
    app: {{.Chart.Name}}
  ports:
    - port: {{.Values.postgres.ports.port}}
      targetPort: {{.Values.postgres.ports.targetPort}}
      protocol: {{.Values.postgres.ports.protocol}}
