apiVersion: v1
kind: Service
metadata:
  name: {{.Values.postgres.service-name}}
  labels:
    name: {{.Values.postgres.service-name}}
    app: {{.Charts.Name}}
spec:
  type: ClusterIP
  selector:
    name: {{.Values.postgres.pod-name}}
    app: {{.Charts.Name}}
  ports:
    - port: {{.Values.postgres.ports.port}}
      targetPort: {{.Values.postgres.ports.targetPort}}
      protocol: {{.Values.postgres.ports.protocol}}
