apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod
  labels:
    name:fastapi-pod
    app: fastapi
spec:
  conatiners:
    - name: fastapi-docker-image
      image: my-fastapi-new
      ports:
       - containerPort: 8000