apiVersion: v1
kind: Pod
metadata:
  name: fastapi-Pod
  labels:
    app: my-fastapi-app-new
    component: fastapi
spec:
  containers:
    - name: fastapi-container
      image: my-fastapi-new
      ports:
        - containerPort: 8000
