apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-deployment
  labels:
    name: postgre-deployment
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
     name: postgres-pod
     app: fastapi
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: fastapi
    spec:
      containers:
        - name: postgres-db-1
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: b25cs1060
            - name: POSTGRES_PASSWORD
              value: Micdrop7!
            - name: POSTGRES_DB
              value: student_course_database
          ports:
          ports:
            - containerPort: 5432
 