apiVersion: v1
kind: Pod
metadata:
  name: postgres-Pod
  labels:
    app: my-fastapi-app-new
    component: postgres
spec:
  containers:
    - name: postgres-container
      image: postgres:13
      ports:
        - containerPort: 5432
