prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 200m
        memory: 400Mi

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: admin123
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-created.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true